### ISSUE TITLE
Protocol out of date

### ISSUE THREAD

**Issue by Addy771** [LiamBindle/PyVESC#10]
Hello and thank you for the excellent work you have done with PyVESC.

I am using PyVESC for a data logging script. When I got the script running, I noticed that some of the values from the GetValues message response were incorrect. 

Here is a thread by another user who discovered the same problem: https://vesc-project.com/node/281

It seems that the new firmware (probably since version 3.xx) provides different values for the GetValues response. I modified my copy of messages/getters.py, replacing the fields in the GetValues class with the following: 

    fields = [
            ('temp_fet', 'h', 10),
            ('temp_motor', 'h', 10),
            ('current_motor', 'i', 100),
            ('current_in', 'i', 100),
            ('avg_id', 'i', 100),
            ('avg_iq', 'i', 100),
            ('duty_now', 'h', 1000),
            ('rpm', 'i', 1),
            ('v_in', 'h', 10),
            ('amp_hours', 'i', 10000),
            ('amp_hours_charged', 'i', 10000),
            ('watt_hours', 'i', 10000),
            ('watt_hours_charged', 'i', 10000),
            ('tachometer', 'i', 1),
            ('tachometer_abs', 'i', 1),
            ('mc_fault_code', 'c'),
            ('unknown', 'i', 1)            
    ]

Now I am getting proper values in my GetValues response. Other messages may also have been changed, but I haven't used the other messages for my application.

**Comment by LiamBindle** [comment]
Hey, thanks for bringing this up. I think you're right, it looks like parts of the protocol have been updated recently. 

It seems like you have a good grasp on what needs to be updated and I see you've forked the project. Are you able to make these changes? If so let me know if you have any questions or need clarification on anything.

**Comment by LiamBindle** [comment]
Sounds good, no worries. I haven't been working on this project for a little while now and I'm not sure when/if I will have time to look into the protocol update.

I will mark it as "todo" and "help wanted" until someone (myself or someone else) makes the pull request.

**Comment by alexwhittemore** [comment]
@Addy771 Great note, thank you for mentioning it even though it didn't stop your show! I'm in a similar situation - trying to use python strictly to poll current info from the VESC (for a live data visualization). I wonder what the state of your current system is? If I clone the repo locally at master and `pip3 install -e local/PyVESC/`, I get the following traceback when trying to use the get_values.py example:
```
Traceback (most recent call last):
  File "/Volumes/HDD/Users/alexw/Sync/vesc_code/test.py", line 49, in <module>
    get_values_example()
  File "/Volumes/HDD/Users/alexw/Sync/vesc_code/test.py", line 23, in get_values_example
    ser.write(pyvesc.encode_request(GetValues))
  File "/Volumes/HDD/Users/alexw/Sync/vesc_code/PyVESC/pyvesc/interface.py", line 51, in encode_request
    msg_payload = pyvesc.messages.base.VESCMessage.pack(msg_cls, header_only=True)
  File "/Volumes/HDD/Users/alexw/Sync/vesc_code/PyVESC/pyvesc/messages/base.py", line 100, in pack
    if instance.can_id is not None:
AttributeError: type object 'GetValues' has no attribute 'can_id'
```
This doesn't change if I swap in your version of `fields`. Any thoughts on what I'm doing wrong? Should I not be on master?

**Comment by alexwhittemore** [comment]
If I install from PyPI and just edit that copy, unfortunately I end up back where I started: a whole lot of serial bytes to read, but on example line 27 `(response, consumed) = pyvesc.decode(ser.read(61))` response is a None :(

Maybe because I'm using a VESC 4.12 and the code matches 6?

**Comment by Addy771** [comment]
Using a VESC 4.12 is fine, I'm using a 4.12 board with the latest firmware and it's working fine with my logger. It sounds like you're not receiving data. Are you able to properly connect to your VESC board to the VESC Tool PC software?

Anyways, this is how I receive data in my logging script:
```
#! check if serial buffer has data
if s1.in_waiting > 0:
    input_buffer += s1.read(s1.in_waiting) # Grab the bytes waiting in the serial input


#! enough data for vesc frame?
if len(input_buffer) > 61:
    recv_msg, consumed = pyvesc.decode(input_buffer)
    input_buffer = input_buffer[consumed:] # trim consumed bytes
```

**Comment by alexwhittemore** [comment]
Actually I came across a snippet I guess probably from you in a forum thread. Copying it about directly, I now get data back. The only difference from the provided example that I can see is running everything in a try block - but I’m pretty tired so maybe there’s something else. 

Anyway, my main issue now is that values look wrong. But I haven’t had a chance to A/B test with the tool. I AM using the fields above.

**Comment by raess1** [comment]
Work in progress for https://github.com/raess1/PyVESC-FW3.33
