### ISSUE TITLE
Struct error when reading firmware

### ISSUE THREAD

**Issue by mgagvani** [LiamBindle/PyVESC#31]
I am using an Enertion Focbox 1.2. When I run the `motor_example.py` script I get this error:

```powershell
Traceback (most recent call last):
  File "C:\Users\mgagv\OneDrive\Documents\Senior_Research\VESC\PyVESC\pyvesc\examples\motor_example.py", line 45, in <module>
    run_motor_using_with()
  File "C:\Users\mgagv\OneDrive\Documents\Senior_Research\VESC\PyVESC\pyvesc\examples\motor_example.py", line 10, in run_motor_using_with
    with VESC(serial_port=serial_port) as motor:
  File "c:\users\mgagv\onedrive\documents\senior_research\vesc\pyvesc\pyvesc\VESC\VESC.py", line 38, in __init__
    version = self.get_firmware_version()
  File "c:\users\mgagv\onedrive\documents\senior_research\vesc\pyvesc\pyvesc\VESC\VESC.py", line 127, in get_firmware_version
    return str(self.write(encode_request(msg), num_read_bytes=msg._full_msg_size))       
  File "c:\users\mgagv\onedrive\documents\senior_research\vesc\pyvesc\pyvesc\VESC\VESC.py", line 91, in write
    response, consumed = decode(self.serial_port.read(self.serial_port.in_waiting))      
  File "c:\users\mgagv\onedrive\documents\senior_research\vesc\pyvesc\pyvesc\protocol\interface.py", line 18, in decode
    return pyvesc.protocol.base.VESCMessage.unpack(msg_payload), consumed
  File "c:\users\mgagv\onedrive\documents\senior_research\vesc\pyvesc\pyvesc\protocol\base.py", line 85, in unpack
    data = list(struct.unpack_from(VESCMessage._endian_fmt + msg_type._fmt_fields, msg_bytes, 1))
struct.error: unpack_from requires a buffer of at least 4 bytes for unpacking 3 bytes at 
offset 1 (actual buffer size is 3)
```

I have verified I'm using the correct serial port. Any ideas as to why this is happening @LiamBindle?

**Comment by mgagvani** [comment]
Resolved when I upgraded the VESC firmware to 6.02
