### ISSUE TITLE
Error running documentation sample code

### ISSUE THREAD

**Issue by OmnipresentStudios** [LiamBindle/PyVESC#6]
I am using this code : 
import pyvesc
my_msg = pyvesc.SetDutyCycle(255)
print(my_msg.duty_cycle)
my_packet = pyvesc.encode(my_msg)

Traceback (most recent call last):
  File "pyvesctest.py", line 1, in <module>
    import pyvesc
  File "/usr/local/lib/python2.7/dist-packages/pyvesc/__init__.py", line 1, in <module>
    from pyvesc.interface import *
  File "/usr/local/lib/python2.7/dist-packages/pyvesc/interface.py", line 1, in <module>
    import pyvesc.messages.base
  File "/usr/local/lib/python2.7/dist-packages/pyvesc/messages/__init__.py", line 2, in <module>
    from pyvesc.messages.getters import *
  File "/usr/local/lib/python2.7/dist-packages/pyvesc/messages/getters.py", line 3
    class GetValues(metaclass=VESCMessage):
                             ^
SyntaxError: invalid syntax

**Comment by LiamBindle** [comment]
Hi,
It appears that you are using Python 2.7. PyVESC only supports Python 3.3+. If you have any further problems please let me know!
